id = "http"
name = "HTTP"
description = "JetBrains-style .http files: completion, hover and requests in the terminal"
version = "0.1.1"
schema_version = 1
authors = ["raphael@lty.gg"]
repository = "https://github.com/raphaelluethy/zed-http"

[grammars.http]
repository = "https://github.com/rest-nvim/tree-sitter-http"
rev = "db8b4398de90b6d0b6c780aba96aaa2cd8e9202c"

[language_servers.zed-http-lsp]
name = "HTTP Language Server"
languages = ["http"]

[[capabilities]]
kind = "download_file"
host = "github.com"
path = ["raphaelluethy", "zed-http", "**"]
