id = "http"
name = "HTTP"
description = "HTTP file support with syntax highlighting, runnable requests, and interactive request execution"
version = "0.1.0"
schema_version = 1
authors = ["raphael@lty.gg"]
repository = "https://github.com/raphaelluethy/zed-http"

[language_servers.zed-http-lsp]
name = "HTTP Language Server"
languages = ["HTTP"]

[grammars.http]
repository = "https://github.com/rest-nvim/tree-sitter-http"
rev = "db8b4398de90b6d0b6c780aba96aaa2cd8e9202c"

[[capabilities]]
kind = "download_file"
host = "github.com"
path = ["raphaelluethy", "zed-http", "**"]

[[capabilities]]
kind = "npm:install"
package = "httpyac"
